disabled_rules:
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - identifier_name
opt_in_rules:
  - empty_count
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - trailing_closure
included:
  - Sources
  - Tests
excluded:
  - .build
